services:

  # ==========================================================
  # STREAMLIT APPLICATION
  # ==========================================================

  streamlit:

    build:
      context: .
      dockerfile: Dockerfile.streamlit

    container_name: document-intelligence-app

    ports:
      - "8501:8501"

    depends_on:
      - mcp-server

    volumes:
      - "C:/:/host/C"
      - "D:/:/host/D"
      - "E:/:/host/E"


  # ==========================================================
  # LOCAL MCP SERVER
  # ==========================================================

  mcp-server:

    build:
      context: .
      dockerfile: Dockerfile.mcp

    container_name: document-search-mcp

    ports:
      - "8000:8000"

    volumes:
      - "C:/:/host/C"
      - "D:/:/host/D"
      - "E:/:/host/E"
