services:

  # ==========================================================
  # STREAMLIT APPLICATION
  # ==========================================================

  streamlit:

    build:
      context: .
      dockerfile: Dockerfile.streamlit

    container_name: document-intelligence-app

    ports:
      - "8501:8501"

    depends_on:
      - mcp-server
      - rag-server

    volumes:
      - "C:/:/host/C"
      - "D:/:/host/D"
      - "E:/:/host/E"


  # ==========================================================
  # LOCAL MCP SERVER
  # ==========================================================

  mcp-server:

    build:
      context: .
      dockerfile: Dockerfile.doc_search.rag
    command: python document_search_mcp.py

    ports:
      - "8000:8000"

    volumes:
      - "C:/:/host/C"
      - "D:/:/host/D"
      - "E:/:/host/E"

  rag-server:

    build:
      context: .
      dockerfile: Dockerfile.doc_search.rag
    command: python rag_mcp.py


    ports:
      - "8001:8001"

    volumes:
      - "C:/:/host/C"
      - "D:/:/host/D"
      - "E:/:/host/E"

